[url "ssh://git@bitbucket.org/"]
	pushInsteadOf = https://bitbucket.org/
[url "ssh://git@gitlab.gnome.org/"]
	pushInsteadOf = https://gitlab.gnome.org/
[url "ssh://git@invent.kde.org/"]
	pushInsteadOf = https://invent.kde.org/
[url "ssh://git@codeberg.org/"]
	pushInsteadOf = https://codeberg.org/
[url "ssh://doronbehar@review.jami.net/"]
	pushInsteadOf = https://review.jami.net/
[url "ssh://git@github.com/"]
	pushInsteadOf = https://github.com/
[url "ssh://git@github.com/doronbehar/private."]
	insteadOf = https://github.com/doronbehar/private.
[url "ssh://git@gitlab.com/"]
	pushInsteadOf = https://gitlab.com/
[url "ssh://git@gitlab.com/doronbehar/private."]
	insteadOf = https://gitlab.com/doronbehar/private.

# vim:ft=gitconfig
